---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-trawl-cloud-v1alpha1-networktap
  failurePolicy: Fail
  name: mnetworktap.trawl.cloud
  rules:
  - apiGroups:
    - trawl.cloud
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networktaps
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-trawl-cloud-v1alpha1-networktap
  failurePolicy: Fail
  name: vnetworktap.trawl.cloud
  rules:
  - apiGroups:
    - trawl.cloud
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - networktaps
  sideEffects: None
