//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyzerConfig) DeepCopyInto(out *AnalyzerConfig) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomContent != nil {
		in, out := &in.CustomContent, &out.CustomContent
		*out = new(CustomContentRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyzerConfig.
func (in *AnalyzerConfig) DeepCopy() *AnalyzerConfig {
	if in == nil {
		return nil
	}
	out := new(AnalyzerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyzerSelection) DeepCopyInto(out *AnalyzerSelection) {
	*out = *in
	in.Suricata.DeepCopyInto(&out.Suricata)
	in.Zeek.DeepCopyInto(&out.Zeek)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyzerSelection.
func (in *AnalyzerSelection) DeepCopy() *AnalyzerSelection {
	if in == nil {
		return nil
	}
	out := new(AnalyzerSelection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyzerStatus) DeepCopyInto(out *AnalyzerStatus) {
	*out = *in
	if in.LastRecordTime != nil {
		in, out := &in.LastRecordTime, &out.LastRecordTime
		*out = (*in).DeepCopy()
	}
	if in.UpstreamFetchedAt != nil {
		in, out := &in.UpstreamFetchedAt, &out.UpstreamFetchedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyzerStatus.
func (in *AnalyzerStatus) DeepCopy() *AnalyzerStatus {
	if in == nil {
		return nil
	}
	out := new(AnalyzerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactReference) DeepCopyInto(out *ArtifactReference) {
	*out = *in
	in.VerifiedAt.DeepCopyInto(&out.VerifiedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactReference.
func (in *ArtifactReference) DeepCopy() *ArtifactReference {
	if in == nil {
		return nil
	}
	out := new(ArtifactReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureFailure) DeepCopyInto(out *CaptureFailure) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureFailure.
func (in *CaptureFailure) DeepCopy() *CaptureFailure {
	if in == nil {
		return nil
	}
	out := new(CaptureFailure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureJob) DeepCopyInto(out *CaptureJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureJob.
func (in *CaptureJob) DeepCopy() *CaptureJob {
	if in == nil {
		return nil
	}
	out := new(CaptureJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CaptureJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureJobList) DeepCopyInto(out *CaptureJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CaptureJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureJobList.
func (in *CaptureJobList) DeepCopy() *CaptureJobList {
	if in == nil {
		return nil
	}
	out := new(CaptureJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CaptureJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureJobSpec) DeepCopyInto(out *CaptureJobSpec) {
	*out = *in
	out.TapRef = in.TapRef
	out.MaxSize = in.MaxSize.DeepCopy()
	if in.PolicyRef != nil {
		in, out := &in.PolicyRef, &out.PolicyRef
		*out = new(ImmutablePolicyReference)
		**out = **in
	}
	if in.Trigger != nil {
		in, out := &in.Trigger, &out.Trigger
		*out = new(TriggerSnapshot)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureJobSpec.
func (in *CaptureJobSpec) DeepCopy() *CaptureJobSpec {
	if in == nil {
		return nil
	}
	out := new(CaptureJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureJobStatus) DeepCopyInto(out *CaptureJobStatus) {
	*out = *in
	if in.RunnerJobRef != nil {
		in, out := &in.RunnerJobRef, &out.RunnerJobRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.RequestedAt != nil {
		in, out := &in.RequestedAt, &out.RequestedAt
		*out = (*in).DeepCopy()
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CaptureEndedAt != nil {
		in, out := &in.CaptureEndedAt, &out.CaptureEndedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.PacketCount != nil {
		in, out := &in.PacketCount, &out.PacketCount
		*out = new(int64)
		**out = **in
	}
	if in.SizeBytes != nil {
		in, out := &in.SizeBytes, &out.SizeBytes
		*out = new(int64)
		**out = **in
	}
	if in.Artifact != nil {
		in, out := &in.Artifact, &out.Artifact
		*out = new(ArtifactReference)
		(*in).DeepCopyInto(*out)
	}
	if in.RetentionDeadline != nil {
		in, out := &in.RetentionDeadline, &out.RetentionDeadline
		*out = (*in).DeepCopy()
	}
	if in.Failure != nil {
		in, out := &in.Failure, &out.Failure
		*out = new(CaptureFailure)
		**out = **in
	}
	if in.RunnerResult != nil {
		in, out := &in.RunnerResult, &out.RunnerResult
		*out = new(RunnerResult)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureJobStatus.
func (in *CaptureJobStatus) DeepCopy() *CaptureJobStatus {
	if in == nil {
		return nil
	}
	out := new(CaptureJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomContentRef) DeepCopyInto(out *CustomContentRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomContentRef.
func (in *CustomContentRef) DeepCopy() *CustomContentRef {
	if in == nil {
		return nil
	}
	out := new(CustomContentRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowSnapshot) DeepCopyInto(out *FlowSnapshot) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowSnapshot.
func (in *FlowSnapshot) DeepCopy() *FlowSnapshot {
	if in == nil {
		return nil
	}
	out := new(FlowSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HubbleTriggerContext) DeepCopyInto(out *HubbleTriggerContext) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HubbleTriggerContext.
func (in *HubbleTriggerContext) DeepCopy() *HubbleTriggerContext {
	if in == nil {
		return nil
	}
	out := new(HubbleTriggerContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImmutablePolicyReference) DeepCopyInto(out *ImmutablePolicyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImmutablePolicyReference.
func (in *ImmutablePolicyReference) DeepCopy() *ImmutablePolicyReference {
	if in == nil {
		return nil
	}
	out := new(ImmutablePolicyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceSource) DeepCopyInto(out *InterfaceSource) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceSource.
func (in *InterfaceSource) DeepCopy() *InterfaceSource {
	if in == nil {
		return nil
	}
	out := new(InterfaceSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkTap) DeepCopyInto(out *NetworkTap) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkTap.
func (in *NetworkTap) DeepCopy() *NetworkTap {
	if in == nil {
		return nil
	}
	out := new(NetworkTap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkTap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkTapList) DeepCopyInto(out *NetworkTapList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkTap, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkTapList.
func (in *NetworkTapList) DeepCopy() *NetworkTapList {
	if in == nil {
		return nil
	}
	out := new(NetworkTapList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkTapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkTapSpec) DeepCopyInto(out *NetworkTapSpec) {
	*out = *in
	if in.MirrorInterface != nil {
		in, out := &in.MirrorInterface, &out.MirrorInterface
		*out = new(InterfaceSource)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeInterface != nil {
		in, out := &in.NodeInterface, &out.NodeInterface
		*out = new(InterfaceSource)
		(*in).DeepCopyInto(*out)
	}
	in.Analyzers.DeepCopyInto(&out.Analyzers)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkTapSpec.
func (in *NetworkTapSpec) DeepCopy() *NetworkTapSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkTapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkTapStatus) DeepCopyInto(out *NetworkTapStatus) {
	*out = *in
	if in.LastPacketTime != nil {
		in, out := &in.LastPacketTime, &out.LastPacketTime
		*out = (*in).DeepCopy()
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]TargetStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkTapStatus.
func (in *NetworkTapStatus) DeepCopy() *NetworkTapStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkTapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerResult) DeepCopyInto(out *RunnerResult) {
	*out = *in
	if in.PacketCount != nil {
		in, out := &in.PacketCount, &out.PacketCount
		*out = new(int64)
		**out = **in
	}
	if in.SizeBytes != nil {
		in, out := &in.SizeBytes, &out.SizeBytes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerResult.
func (in *RunnerResult) DeepCopy() *RunnerResult {
	if in == nil {
		return nil
	}
	out := new(RunnerResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuricataTriggerContext) DeepCopyInto(out *SuricataTriggerContext) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuricataTriggerContext.
func (in *SuricataTriggerContext) DeepCopy() *SuricataTriggerContext {
	if in == nil {
		return nil
	}
	out := new(SuricataTriggerContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetStatus) DeepCopyInto(out *TargetStatus) {
	*out = *in
	if in.PodRef != nil {
		in, out := &in.PodRef, &out.PodRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	in.HeartbeatTime.DeepCopyInto(&out.HeartbeatTime)
	if in.LastPacketTime != nil {
		in, out := &in.LastPacketTime, &out.LastPacketTime
		*out = (*in).DeepCopy()
	}
	if in.KernelDrops != nil {
		in, out := &in.KernelDrops, &out.KernelDrops
		*out = new(int64)
		**out = **in
	}
	if in.Analyzers != nil {
		in, out := &in.Analyzers, &out.Analyzers
		*out = make([]AnalyzerStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetStatus.
func (in *TargetStatus) DeepCopy() *TargetStatus {
	if in == nil {
		return nil
	}
	out := new(TargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerSnapshot) DeepCopyInto(out *TriggerSnapshot) {
	*out = *in
	in.EventTime.DeepCopyInto(&out.EventTime)
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	if in.Flow != nil {
		in, out := &in.Flow, &out.Flow
		*out = new(FlowSnapshot)
		**out = **in
	}
	if in.Suricata != nil {
		in, out := &in.Suricata, &out.Suricata
		*out = new(SuricataTriggerContext)
		**out = **in
	}
	if in.Hubble != nil {
		in, out := &in.Hubble, &out.Hubble
		*out = new(HubbleTriggerContext)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerSnapshot.
func (in *TriggerSnapshot) DeepCopy() *TriggerSnapshot {
	if in == nil {
		return nil
	}
	out := new(TriggerSnapshot)
	in.DeepCopyInto(out)
	return out
}
